import type AuthClient from "../../client";
import rewriteUrlWithBase from "../../utils/rewrite-url-with-base";
import { ApiBuilder } from "../../utils/server";
import AbstractClientPlugin from "../abstract-client-plugin";
import { ROUTES } from "./constants";

type CoreClientPluginParams = {
  callback: {};
  options: {};
};

const DEFAULT_OPTIONS = {};

export default class CoreClientPlugin extends AbstractClientPlugin {
    private _callback;
    private _options;
    
    private _accessToken = null; // refresh token is in HTTP_ONLY cookie
    
    constructor (params: CoreClientPluginParams) {
        super();

        this._callback = params.callback;
        this._options = {
            ...DEFAULT_OPTIONS,
            ...params.options,
        };
    }

    public registerApi(authClient: AuthClient) {
        return new ApiBuilder()
            .api('fetch', async (input: RequestInfo | URL, init?: RequestInit, options?: {
                shouldRewriteToBaseUrl?: Boolean,
                shouldInjectAuthHeader?: Boolean,
            }) => {
                const optionWithDefault = {
                    shouldRewriteToBaseUrl: false,
                    shouldInjectAuthHeader: false,
                    ...options, // overwrite our options if they are defined
                };

                // check if accessToken has expired, refresh if needed
                // if refresh token is expired, return error and force login again

                const initWithHeaders = {
                    ...init,
                    ...(optionWithDefault.shouldInjectAuthHeader && {
                        headers: {
                            ...init?.headers,
                            Authorization: `Bearer ${this._accessToken}`,
                        }
                    }),
                };

                // If we are trying to fetch with authentication heders,
                // there is the assumption that we are trying to hit our authServer
                // modify our input url to always route to our authServer baseUrl
                // unless we have opted out via the `customUrl` flag
                return fetch(optionWithDefault.shouldRewriteToBaseUrl ? input : rewriteUrlWithBase(input, authClient.options.baseUrl), initWithHeaders)
            })
            .api(
                'handleTokenResponse',
                /**
                 * 
                 * @param res A Response generated by authServer.api.tokenResponse(user)
                 * @returns 
                 */
                async (res: Response) => {
                    try {
                        const json = await res.json();

                        if (!json.accessToken) {
                            throw 'No access token in tokenResponse';
                        }

                        // save access token for us to use in later requests
                        this._accessToken = json.accessToken;

                        return {
                            success: true,
                            error: null,
                            message: 'Successfully logged in',
                        }
                    } catch (err) {
                        // something went wrong, log the current user out and surface error message to prompt them to try again
                        await this.cleanupTokens(new URL(`${authClient.options.baseUrl}${ROUTES.LOGOUT}`));

                        return {
                            success: false,
                            error: typeof err === "string" ? err : "Unknown error occured in tokenResponse",
                            message: "Unable to login, please try again",
                        }
                    }
                }
            );
    }

    private async cleanupTokens(logoutUrl: URL) {
        // send request to logout route to clear refresh token cookie
        try {
            const res = await fetch(logoutUrl); // NOTE: unauthenticated fetch
            const json = await res.json();

            // delete access token in memory
            this._accessToken = null;
        } catch (err) {

        }
    }
}